import ContainerRoot from "@components/Containers/ContainerRoot";
import "../styles/global.css";

export const metadata = {
  title: "schetine",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-950">
        <ContainerRoot>{children}</ContainerRoot>
      </body>
    </html>
  );
}
