import { ContainerPublicRoutes } from "@components/Containers/ContainerPublicRoutes";
import ContainerRoot from "@components/Containers/ContainerRoot";

export const metadata = {
  title: "schetine",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ContainerPublicRoutes>{children}</ContainerPublicRoutes>;
}
