version: '3'
services:
  db: 
    container_name: postgres_database
    image: postgres:14.3-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: schetine
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - 5432:5432
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
    networks: 
      - default