import { ContainerApp } from "@components/Containers/desktop/ContainerApp";

export const metadata = {
  title: "schetine",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ContainerApp>{children}</ContainerApp>;
}
